import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import LanguageProviderWrapper from "./LanguageProviderWrapper";

const geist = Geist({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
  display: 'swap',
  variable: '--font-geist-sans'
});

export const metadata: Metadata = {
  title: "ApplyLabs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geist.variable} ${geist.className}`}>
      <body>
        <LanguageProviderWrapper>
          {children}
        </LanguageProviderWrapper>
      </body>
    </html>
  );
}
